# system related
cuda: True
gpu: ??
logger_name: ??
seed: 42

# data related
data_path: data/
batch_size: 10
which_dataset: MNIST_binary

# optimizer
optimizer: SGD  # AdamW
lr: ??  # 0.0001
wd: 0.
momentum: 0.
criterion: "MSE"

# model related
arch: shallow_NN
num_hidden: 250

# training related
total_iter: 5000
iter_period: 5000
prune_iter: 0
debias_iter: 5000
log_freq: 5
save_freq: 500


# hyper parameter
#threshold: 0.001
