# system related
cuda: True
no_cuda: ??
gpu: ??
logger_name: ??
seed: 44

# data related
data_path: data/
batch_size: 10
which_dataset: MNIST_subset
samps_per_class: 10

# optimizer
optimizer: SGD  # AdamW
lr: ??  # 0.0001
wd: 0.
momentum: 0.
criterion: "MSE"

# model related
arch: shallow_NN
num_hidden: 5000

# training related
total_iter: 10003
iter_period: 10003
prune_iter: 0
debias_iter: 10003
log_freq: 5
save_freq: 100


# hyper parameter
#threshold: 0.001
