# system related
cuda: True
gpu: ??
logger_name: ??
seed: 42

# data related
data_path: data/
batch_size: 10
samps_per_class: 50
which_dataset: MNIST_binary_synth

# optimizer
optimizer: SGD  # AdamW
lr: ??  # 0.0001
wd: 0.
momentum: 0.
criterion: "MSE"

# model related
arch: shallow_NN
num_hidden: 1000

# training related
total_iter: 10000
iter_period: 10000
prune_iter: 0
debias_iter: 10000
log_freq: 10
save_freq: 1000


# hyper parameter
#threshold: 0.001
